
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#Можно ли генерировать корабли снабжения и лагеря в сундуках с награбленным добром. [По умолчанию: true]
	generatesupplyloot = true

#Все настройки, связанные с системой запросов
[requestsystem]
	#Следует ли системе запросов отображать отладочную информацию в debug.log? Полезно при сбоях. [По умолчанию: false]
	enabledebuglogging = false

