#Disables the fur border at the screen edge in werewolf form
disableScreenFurRendering = true
#Disables fangs crosshair when you can bite in werewolf form
disableFangCrosshairRendering = true

[internal]
	#If the mca integration message was send
	mcaMessage = false

