#how many ticks invisibility should be nullified for after an attack. The invisibility potion effect is not removed, so long-lasting sources are still useful. Set to 0 to disable.
#Range: > 0
"damage expose time" = 160
#on every detection check your stealth is increased by a random number rolled between 0 and the difference of your and your enemy's luck. This multiplier applies to the resultant effective stealth increase (or decrease!). Set to 0 to disable.
#Range: 0.0 ~ 100.0
"luck stealth" = 0.5
#whether you must pass stealth checks to perceive a mob. Currently rather incomplete. I am not responsible for ragequits caused by this option. This physically ceases to work with Optifine installed.
"use player senses" = false
#angle of detection on the xz plane
#Range: 0 ~ 360
"default mob horizontal FoV" = 120
#angle of detection on the y axis
#Range: 0 ~ 360
"default mob vertical FoV" = 90
#posture and health damage multiplier for distracted stabs
#Range: 0.0 ~ 1.7976931348623157E308
"distracted stab multiplier" = 1.5
#posture and health damage multiplier for unaware stabs
#Range: 0.0 ~ 1.7976931348623157E308
"unaware stab multiplier" = 1.5
#whether unaware stabs ignore parry, deflection, shatter, and absorption
"unaware stab defense ignore" = true

